name: Publish Docs MCP to npm

on:
  push:
    tags:
      - "v*" # Trigger on tags like v1.0.0, v1.1.0, etc.
  schedule:
    - cron: '0 0 * * *' # Trigger daily at 00:00 UTC
  workflow_dispatch: # Allow manual triggering from the GitHub UI

permissions:
  contents: read # Needed to check out the repository

jobs:
  publish-npm:
    name: Publish @buger/probe-docs-mcp to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Remove 'v' prefix from tag (e.g., v1.0.0 -> 1.0.0)
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"
          scope: "@buger"

      - name: Install dependencies
        run: npm install

      - name: Update package version
        if: env.VERSION != ''
        run: |
          npm version ${{ env.VERSION }} --no-git-tag-version
          echo "Updated package.json to version ${{ env.VERSION }}"

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
